### PR TITLE
Add a poster image public property

### PR DESCRIPTION
**Pull request by storix**
This _posterImage_ property can be used to get a preview image of an animated GIF.

### CODE REVIEW

**Comment by kaishin** [comment]
@storix Is there a compelling reason we need to introduce another property instead of just setting the `image`?

**Comment by storix** [comment]
@kaishin `image` is constantly changing when GIF is progressing. I just thought we can use posterImage property as a convenient way to get the first GIF frame whenever we want. But, you know, i'm now pondering maybe it would be even better to have a method like "getFrameAtIndex..."? Would like to know your thoughts.

And here is another issue. According to my tests this line `image = UIImage(data: data)` in `prepareForAnimation(imageData data: NSData)` has such running time: 0.002319 seconds. But as we call `animator?.prepareFrames()` anyway we can change it to something like this `image = (animator?.animatedFrames.count > 0) ? animator?.animatedFrames[0].image : nil` And after that it becomes better: 0.000038 seconds. I think, this should be taken into account.
.

**Comment by kaishin** [comment]
Sorry @storix I went ahead and merged the bug fixes first. I will go over this PR and the others next.

**Comment by storix** [comment]
@kaishin It's ok. By the way, I have reworked this PR taking into account new considerations.I'll submit it later. For now I'm closing it so you won't be wasting your time verifying this.

**Pull request closed without merging**
