### PR TITLE
remove .submodule because it seems to have unused submodule Runes

### PR DESCRIPTION
**Pull request by evgeniyd**
This is a fix for Issue #71

### CODE REVIEW

**Comment by onato** [comment]
Is there any reason why this PR has not been merged? It fixes the issue for me and seems completely reasonable.

**Comment by evgeniyd** [comment]
@onato hi, I don't know the details, so it is better to hear some feedback from the author.

**Comment by kaishin** [comment]
Sorry for the delay. I've been busy with life but I've got time to dedicate to this library again.

**Comment by evgeniyd** [comment]
@kaishin no probs. 
Thank you for the review.

**Pull request merged**
