### PR TITLE
Ported to Swift 3

### PR DESCRIPTION
**Pull request by askari01**
Migrated Code to Swift 3
- using lot of resources (needs to be fixed)

### CODE REVIEW

**Comment by kaishin** [comment]
Thanks for opening the PR but this is already underway in the https://github.com/kaishin/Gifu/tree/swift3 branch. Did you miss that or does this add things that weren't in there?

**Comment by askari01** [comment]
it is consuming too much of CUP resources; have you looked into it @kaishin

**Comment by kaishin** [comment]
@askari01 The whole point of the library is to balance CPU and memory usage. Going all in on memory is not good either, especially if the gif is large. If you are not happy with the CPU usage, you need to increase the `frameBufferCount` of the `Animator` instance of `GIFImageView`.

**Comment by askari01** [comment]
i should try to increase the buffer count, will posts results afterwards

**Comment by kaishin** [comment]
@askari01 If you are on `master` I just added [this helper method](http://kaishin.github.io/Gifu/Protocols/GIFAnimatable.html#/s:FE4GifuPS_13GIFAnimatable19setFrameBufferCountFSiT_) to remove the need to tinker directly with the animator instance.

**Pull request closed without merging**
