### PR TITLE
Change deployment target to 8.0 to prevent issue #75

### PR DESCRIPTION
**Pull request by chickdan**

### CODE REVIEW

**Comment by kaishin** [comment]
Not sure I understand the problem this is trying to solve and how it does solve it. The library is supposed to work with iOS 9.0 and up, the reason being not having to debug and monitor performance on iOS 8 as well.

**Comment by chickdan** [comment]
Unfortunately it doesn't work with iOS 9.0 and up, I'm experiencing the same behavior as in issue #75 where the images don't even display. Once I dropped the target back down to iOS 8.0 it worked again.

**Comment by kaishin** [comment]
@chickdan The demo on `master` is targeting 9.0 and up and it works just fine. Is this related to loading GIFs from the asset catalog?

**Comment by chickdan** [comment]
The change is for the swift2.3 branch, but yes I believe it is related to loading GIFs from the asset catalog.

**Pull request merged**
