### PR TITLE
Move an animation to a specific frame

### PR DESCRIPTION
**Pull request by stanmots**
_moveToFrame_ public function makes it possible to move an animation to a required GIF frame. It works according to the following algorithm: 
1) Stop currently played animation;
2) Extract GIF frame in accordance with the given index;
3) Display this frame;
4) Rebuild the cache (_animatedFrames_ array) during the next animation starting procedure.

### CODE REVIEW

**Comment by kaishin** [comment]
@storix Does this still depend on #38? In which order you prefer them to be merged?

**Comment by storix** [comment]
@kaishin No. #38 is deprecated. You can review and merge this PR completely independently now.

**Comment by kaishin** [comment]
Ditto https://github.com/kaishin/Gifu/pull/42#issuecomment-249437030

**Comment by kaishin** [comment]
Will reopen to keep track of the feature.

**Comment by rk85097** [comment]
Any plans on adding this functionality? I really need it :)

**Comment by kaishin** [comment]
@rk85097 No concrete plans, but if ou want to look at the PR as a reference and make the changes necessary in the current version that would be terrific.

**Pull request closed without merging**
